# Generated by Django 3.2.9 on 2021-11-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
    ]
